/* 
 * ©2015 EdgeVerve Systems Limited, Bangalore, India. All Rights Reserved.
 *
 * The EdgeVerve proprietary software program ("Program"), is protected by copyrights laws, international treaties
 * and other pending or existing intellectual property rights in India, the United States and other countries. The Program
 * may contain / reference third party or open source components, the rights to which continue to remain with the applicable
 * third party licensors or the open source community as the case may be and nothing here transfers the rights to the third party
 * and open source components, except as expressly permitted. Any unauthorized reproduction, storage, transmission in any
 * form or by any means (including without limitation to electronic, mechanical, printing, photocopying, recording or 
 * otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be
 * prosecuted to the maximum extent possible under the law.
 * 
 */
var sc_language = window.sc_language = {

	// Start translations from below lines. Do not change left hand side
	// text of ':';
	"shoppingCart_colon_label" : ":",
	"shoppingCart_my_cart" : "My Cart",
	"shoppingCart_save_cart_for_later" : "Save Cart For Later",
	"shoppingCart_continue_shopping" : "Continue Shopping",
	"shoppingCart_save_for_later":"Save For Later",
	"shoppingCart_remove_sobo":"Remove Sobo",
	"shoppingCart_proceed":"Proceed",
	"shoppingCart_currency":"Currency",
	"shoppingCart_uom": "Unit of Measure",
	"shoppingCart_checkout" : "Checkout",
	"Shopping_Cart" : "Shopping Cart",
	"shoppingCart_shoppingcartno_title" : "Shopping Cart Number",
	"shoppingCart_items" : "Item(s)",
	"shoppingCart_sub_part_name" : "Sub Part Name",
	"shoppingCart_required_on_date" : "Required On Date",
	"shoppingCart_required_on" :"Required On",
	"shoppingCart_goods" :"Goods",
	"shoppingCart_quantity" : "Quantity",
	"shoppingCart_cart_name" : "Cart Name",
	"shoppingCart_enter" : "Enter",
	"shoppingCart_per_units" : "per unit(s)",
	"shoppingCart_item_total" : "Item Total",
	"shoppingCart_delete" : "Delete",
	"shoppingCart_cart" : "Cart",
	"shoppingCart_cart_price_Zero_error_message" : "Warning: This will create a Zero Value Order",
	"shoppingCart_delete_cart":"Delete Cart",
	"shoppingCart_save" : "Save",
	"shoppingCart_changes" : "Changes",
	"shoppingCart_change_picture" : "Change Picture",
	"shoppingCart_profile" : "Profile",
	"shoppingCart_delivery_info" : "Delivery Info",
	"shoppingCart_shop_for" : "Shop For",
	"shoppingCart_service_request" : "Service Request",
    "supplier_details_sobo_conf1":"User profile default settings of selected user will be applied to the Shopping Cart.",
    "supplier_details_sobo_conf2": "Do you want to continue?",
    "shoppingCart_cart_account_type": "Account Type",
	"shoppingCart_service" : "Service",
	"shoppingCart_manage_substitution" : "Manage Substitution",
	"shoppingCart_log_out" : "Log Out",
	"shoppingCart_personal" : "Personal",
	"shoppingCart_information" : "Information",
	"shoppingCart_first_name" : "First Name",
	"shoppingCart_last_name" : "Last Name",
	"shoppingCart_country" : "Country",
	"shoppingCart_fft_description":"Enter FFT description here...",
	"orderSummary_state":"State",
	"orderSummary_city":"City",
	"orderSummary_zip_code":"Zip Code",
	"shoppingCart_recipient_name":"Recipient Name",
	"shoppingCart_add_to_favourites":"Add to favourites",
	"shoppingCart_remove_from_favorites":"Remove from favourites",
	"shoppingCart_remove":"Remove",
	"shoppingCart_deliver_to":"Deliver to",
	"shoppingCart_apply_to_all_items":"",
	"shoppingCart_supplier_attachmert":"Supplier attachment",
	"shoppingCart_server_document_powerhouse":"Server Document powerhouse",
	"shoppingCart_address":"Address",
	"shoppingCart_add_to_my_address_list":"Add to my Address list",
	"shoppingCart_send_to_supplier":"Send to supplier",
	"shoppingCart_add_notes":"Add Notes",
	"shoppingCart_emailId" : "Email Id",
	"shoppingCart_userId" : "User Id",
	"shoppingCart_fileUpload_error_message": "Please upload file by clicking on attachment button",
	"please_enter_expected_price":"Please enter expected Price",
	"incorrect_decimal_format":"Incorrect decimal format.Please enter appropriate numeric value",
	"EHSR_Information":"EHSR Information",
	"CAS_Information":"CAS Information",
	"please_enter_required_quantity":"Please enter appropriate numeric value",
	"please_enter_quantity_greater_than_zero":"Please enter quantity greater than zero",
	"please_enter_item_description":"Please enter item description",
	"please_enter_required_unit":"Please enter required unit",
	"shoppingCart_manager" : "Manager",
	"shoppingCart_preferences" : "Preferences",
	"shoppingCart_done": "Done",
	"sc_account_costAllocationPopupColValue": "Value",
	"sc_account_costAllocationPopupColName": "Name",
	"shoppingCart_delete_cart_confirmation_message" : "Are you sure you want to delete this Shopping Cart?",
	"shoppingCart_yes" : "Yes",
	"shoppingCart_no" : "No",
	"shoppingCart_delete_item_confirmation_message" : "Are you sure you want to delete this item?",
	"shoppingCart_confirm" : "Confirm",
	"shoppingCart_save_cart_confirmation_message" : "This cart will be moved to Saved Shopping Carts. You may activate this Cart later to complete your order. <br/><br />Do you want to continue?",
	"shoppingCart_no_data" : "There are currently no items in your Shopping Cart.",
	"shoppingCart_save_cart_later_msg" : "has been saved.",
	"shoppingCart_view_saved_cart_msg" : "View Saved Carts",
	"shoppingCart_view_my_orders_msg" : "My Orders",
	"shoppingCart_qotes" : "&#34;",
	"shoppingCart_bulk_order" : "Catalog Shopping via Excel Upload",
	"shoppingCart_drop_excel_here" : "Drop Excel Here",
	"shoppingCart_browse" : "Browse",
	"shoppingCart_or" : "OR",
	"shoppingCart_download_template" : "Download Template",
	"shoppingCart_upload_more_files" : "Upload more files",
	"shoppingCart_add_items" : "Add Items",
	"shoppingCart_no_attachments" : "No Attachments Found ! !",
	"shoppingCart__attachments" : "Attachments",
	"shoppingCart_upload_more_files" : "Upload more files",
	"shoppingCart_reference_no" : "Reference No",
	"shoppingCart_createdon_title" : "Created on",
	"shoppingCart_suppliername_title" : "Supplier Name",
	"shoppingCart_service_code" :"Service Code Number",
	"shoppingCart_supplierpartnumber_title" : "Supplier Part Number",
	"shoppingCart_lastsavedon_title" : "Last Saved On",
	"shoppingCart_price_title": "Price",
	"shoppingCart_priceactivitybased_title" : "Activity Based",
	"shoppingCart_volumepricing_title" : "Volume Pricing",
	"shoppingCart_per_title": "per",
	"shoppingCart_Per_title" : "Per",
	"shoppingCart_units_title": "unit(s)",
	"shoppingCart_base_price":"Base Price",
	"shoppingCart_landing_price":"Landing Price",
	"shoppingCart_service_code":"Service Code",
	"shoppingCart_amount_title" : "Amount",
	"shoppingCart_supplierPannel_goods_item_example":"Supplier Panel Goods item Example",
	"shoppingCart_numbers":"Numbers",
	"shoppingCart_service_code_number":"Services Code Number",
	"shoppingCart_fft_services_item_example":"FFT Services item Example",
	"shoppingCart_fft_goods_item_example":"FFT Goods item Example",
	"shoppingCart_units_of_measure":"Units of Measure",
	"shoppingCart_activitybased_title":"Activity Based",
	"shoppingCart_servicestart_title": "Service Start",
	"shoppingCart_serviceend_title": "End Date",
	"shoppingCart_to_title" : "to",
	"shoppingCart_characters_left" : "Characters left",
	"shoppingCart_volumepricing_title" : "Volume Pricing",
	"shoppingCart_peritem_title" : "per",
	"shoppingCart_deleteditems_title": "Following item(s) from this Cart have been removed as they are no longer available in catalog.",
	"shoppingCart_items_title": "Item(s)",
	"shoppingCart_ok_title": "Ok",
	"shoppingCart_allitemdeleted_title": "Sample text goes here...",
	"shoppingCart_edit_title" : "Edit",
	"shoppingCart_save_title" : "Save",
	"shoppingCart_delete_title" : "Delete",
	"shoppingCart_attach_title" : "Attach",
	"sc_accountType":"Account Type",
	"sc_percentSymbol":"%",
	"sc_accountObjects":"Account Objects",
	"sc_splitTypePercentage":"Percentage",
	"sc_splitTypeAmount":"Amount",
	"sc_splitTypeQuantity":"Quantity",
	"sc_buttonSplitAccount":"Split Account",
	"sc_buttonToolTipDeleteAllocation":"Delete",
	"sc_account_assignment":"Account Assignment",
	"sc_account_searchByNameOrValue":"Search by Name or Value",
	"sc_account_costAllocationPopupCloseLabel":"Done",
	"BE_SC_1000_1" : "Invalid Request",
	"BE_SC_1000_2" : "Price details are not available. Unable to add item to Shopping Cart.",
	"BE_SC_1000_3" : "This item cannot be added to Shopping Cart as the active Shopping Cart contains FFT items.",
	"BE_SC_1000_4" : "Unable to add item to Shopping Cart. Shopping Cart has a limit of 100 items.",
	"BE_SC_1000_5" : "This item is no longer available in catalog.Unable to add item to Shopping Cart.",
	"BE_SC_1000_6" : "For Rate based items : Quantity cannot be zero.",
	"BE_SC_1000_7" : "For Rate based items : Quantity entered should be greater than or equal to Minimum Order Quantity. Please enter a value greater than or equal to {{min}}",
	"BE_SC_1000_8" : "For Rate based items : Quantity entered should be a multiple of the order interval. Please enter value in multiples of {{orderInterval}}",
	"BE_SC_1000_9" : "For activity based items : Amount cannot be zero.",
	"BE_SC_1000_10" : "Quantity entered should be greater than or equal to Minimum Order Quantity. Please enter a value greater than or equal to {{min}}",
	"BE_SC_1000_11" : "Quantity entered should be a multiple of the order interval. Please enter value in multiples of {{orderInterval}}",
	"BE_SC_1000_12" : "This item cannot be added to Cart. Please contact ProcureEdge Support.",
	"BE_SC_1000_13" : "Please enter a today’s date or date later than today’s date",
	"BE_SC_1000_14" : "Please enter a today’s date or date later than today’s date",
	"BE_SC_1000_15" : "Please enter a today’s date or date later than today’s date",
	"BE_SC_1000_16" : "Service Start Date cannot be later than Service End Date",
	"BE_SC_1000_17" : "NA",
	"BE_SC_1000_18" : "NA",
	"BE_SC_1000_19" : "Unable to save this Shopping Cart. You can have maximum 100 Saved Carts in your profile.",
	"BE_SC_1000_20":"The maximum limit for attachments of 10 MB has been exceeded. The file you are trying to attach cannot be uploaded. Please remove other attachments and try again.",
	"BE_SC_1000_45" : "Please select a valid UOM from the available list.",
	"BE_SC_1000_46": "Please select a valid Currency from the available list.",
	"BE_SC_1000_21":"The file you are trying to attach cannot be uploaded. You can upload file of up to {{fileSize}} MB size.",
	"BE_SC_1000_39":"Please enter numeric distribution for cost allocation.",
	"BE_SC_1000_40":"Allocation total should be 100%. Please update allocation values.",
	"BE_SC_1000_41":"Allocation total should be equal to quantity of item. Please update allocation values.",
	"BE_SC_1000_42":"Allocation total should be equal to item subtotal. Please update allocation values.",
	"BE_SC_1000_47":"Please select a valid Plant from the available list.",
	"BE_SC_1000_48":"Please select Plant",
	"SYSTEM_ERROR" : "Unable to perform your current action. Please contact ProcureEdge Support.",
	"shoppingCart_later_year_service_warning" :	'Warning : Service Start Date is later than one year from today\'s date.',
	"shoppingCart_later_year_product_warning" : 'Warning : Required on Date is later than one year from today\'s date.',
	"shoppingCart_lead_date_service_warning" :	'Warning : Service Start Date is earlier than the service initiation time indicated by the Supplier. Suppliers may or may not be able to meet the date and timelines.',
	"shoppingCart_lead_date_goods_warning" : 'Warning : Required on Date is earlier than the lead time indicated by the Supplier. Suppliers may or may not be able to meet the date and timelines.',
	"shoppingCart_pricevaliditydate_today_warning" : "Warning : Price validity date provided by Supplier is earlier than today\'s date. Supplier may or may not be able to provide this item/service at this price.",
	"shoppingCart_pricevaliditydate_requiredon_warning" : "Warning : Price validity date provided by Supplier is earlier than Required on Date. Supplier may or may not be able to provide this item/service at this price.",
	"shoppingCart_pricevaliditydate_servicestart_warning" : "Warning : Price validity date provided by Supplier is earlier than Service Start Date. Supplier may or may not be able to provide this item/service at this price.",
	"shoppingCart_file_success_message":"Adding Supplier Attachment. Please Wait ! !",
	"shoppingCart_file_supp_attachments":"Attachments for Supplier",
	"shoppingCart_name_empty" : "Shopping Cart name can not be empty",
	"shoppingCart_name":"Shopping Cart Name",
	"shoppingCart_invalid_cart_name" :	"Invalid Shopping Cart Name",
	"shoppingCart_dropzone_size_error" :	"The file you are trying to attach cannot be uploaded. You can upload file of up to {{fileSize}} MB size.",	
	"shoppingCart_dropzone_folder_error" :	"Folder cannot be uploaded, Please upload a single file.",
	"shoppingCart_dropzone_multiple_files_error" : "Multiple file cannot be uploaded, Please upload a single file",
	"shoppingCart_dropzone_system_error" : "Unable to perform your current action. Please contact ProcureEdge Support.",
	"shoppingCart_item_attachment_empty_error" : "Please upload the additional information as per the template. No files attached.",
	"shoppingCart_itemquantity_empty" : "Please enter appropriate numeric value in given format:",
	"SE_SC_ATTACHMENT_EXCEPTION": "System could not attach the file. Please contact the support team for assistance.",
	"PE_SC_ATTACHMENT_EXCEPTION": "System could not attach the file. Please contact the support team for assistance.",
	"SC_MIME_TYPE_EXCEPTION1" : "You can't upload file of this type. Kindly upload file of type ",
	"shoppingCart_dropzone_filename_error" : "The file you are trying to attach cannot be uploaded. File name should not contain any special characters except '_' and '-'.",
	"shoppingCart_round_constant" : "_R",
	"shoppingCart_price_validity_date" : "Price Validity Date",
	"orderSummary_startDate_title" : "Start Date",
	"shoppingCart_split_account":"Split Account",
	"orderSummary_endDate_title" : "End Date",
	"orderSummary_supplier_title" : "Supplier",
	"orderSummary_supplier_product_number" : "Supplier Product Number",
	"orderSummary_category_title" : "Category",
	"orderSummary_sobo_title":"Shop on behalf of",
	"orderSummary_companyCode_title":"Company Code",
	"orderSummary_manufacturePartNo_title":"Manufacturer Part Number",
	"orderSummary_ehsrInformation_title":"EHSR Information",
	"orderSummary_casInformation_title":"CAS Information",
	"orderSummary_deliveryDetails_title":"Delivery Details",
	"shoppingCart_plant_code":"Plant Code",
	"orderSummary_accountAssignment_title":"Account Assignment",
	"orderSummary_accountType_title":"Account Type",
	"orderSummary_accountObjects_title":"Account Objects",
	"orderSummary_notes_title":"Notes",
	"orderSummary_attachmentsToBuyer_title":"Attachments to Buyer",
	"orderSummary_attachments":"Attachments",
	"orderSummary_costCenter_title":"Cost Center",
	"orderSummary_fixedAssetNumber_title":"Fixed Asset Number",
	"shoppingCart_percentage":"Percentage",
	"orderSummary_placeOrder_button":"Place Order",
	"orderSummary_placeOrder_msg1":"Your order for ",
	"orderSummary_placeOrder_msg2":"(Shopping Cart Number : ",
	"orderSummary_placeOrder_msg3":") has been placed successfully.",
	"orderSummary_placeOrder_msg4":") has been already placed.",
	"orderSummary_placeOrder_error":"Unable to process your request. Please try after some time.",
	"shoppingCart_placeOrder_error":"Unable to process your request. Please try after some time.",
	"orderSummary_placeOrder_msg":"Your order for {{cartName}} (Shopping Cart Number : {{cartNumber}} ) has been placed successfully.",
	
	"recipient_title" : "Recipient",
	"recent_recipient_title" : "Recently Used",
	"recipient_typeAHead_placeHolder" : "Search by Employee Name, ID or Email",
	"orderSummary_trackOrders":"You can track your order MyOrders.",
	"orderSummary_placeOrder_fft":"Free Form Text",
	"orderSummary_placeOrder_supplierPannel":"Supplier Panel",
	"sobo_title" : "Shop On Behalf Of",
	"recent_sobo_title" : "Recently shopped on behalf of",
	"sobo_typeAHead_placeHolder" : "Search by Employee Name, ID or Email",
	"sobo_done" : "Done",
	"sobo_change" : "Change",
	"shoppingCart_percent":"percent",
	"supplier_details_title":"Supplier Details",
	"supplier_details_placeHolder":"Search by Supplier Code or Name",
	"shoppingCart_loading_please_wait":"Loading, please wait...",
	"supplier_details_code":"Supplier Code",
	"supplier_details_name":"Supplier Name",
	"supplier_details_done":"Done",
	"supplier_details_all":"All Suppliers",
	"supplier_details_preferred":"Preferred Suppliers",
	"supplier_details_no_data":"No Data Found",
	"shoppingCart_tile_mixcart_error" : "This item cannot be appended to existing Shopping Cart as it contains {{ItemType}} item(s). If you proceed, new Shopping Cart will be created and existing Shopping Cart will be auto-saved. Do you want to continue?",
	"shoppingCart_requiredtill_greater_year": "Warning : Date entered is later than one year from today’s date. Suppliers may or may not be able to meet the date and timelines.",
	"shoppingCart_servicestart_greater_year": "Warning : Date entered is later than one year from today’s date. Suppliers may or may not be able to meet the date and timelines.",
	"shoppingCart_servicetill_greater_year": "Warning : Date entered is later than one year from today’s date. Suppliers may or may not be able to meet the date and timelines.",
	"shoppingCart_country_error":"Please select country",
	"shoppingCart_state_error":"Please select state",
	"shoppingCart_ntoes":"Enter notes here...",
	"shoppingCart_city_error":"Please select city",
	"shoppingCart_uom_error":"Please select a valid UOM from the available list.",
	"shoppingCart_currency_error":"Please select a valid Currency from the available list.",
	"shoppingCart_costAllocatoin_accountList_empty_message":"There are no account types mapped to the selected company code in the cart.",
	"shoppingCart_all_title" : "All",
	"shoppingCart_recently_used_title" : "Recently Used",
	"shoppingCart_search_title" : "Search",
	"shoppingCart_external":"External",
	"shoppingCart_noresults_title" : "No Results Found",
	"shoppingCart_options_label":"Optional",
	"shoppingCart_order_summary":"Order Summary",
	"shoppingCart_edit_order":"Edit Order",
	"numeric_value_greater_than_zero":"Please enter appropriate numeric value greater than zero",
	"savedForLater":"This cart will be moved to Saved Shopping Carts. You may activate this Cart later to complete your order. <br><br>Do you want to continue?",
	"sc_myaddress_title" : "My Addresses",
	"sc_standartaddress_title" : "Standard Addresses",
	"sc_nomatchfounc_title": "No matches found",
	"sc_sobo_not_selected_error":"Please select user from the list to proceed",
	"shoppingCart_partial_template":"Template",
	"shoppingCart_apply_to_all_items":"Apply to all items",
	"shoppingCart_companycodelist_error":"No companies are mapped to the current user in the system. Please contact system administrator for getting the data issue resolved.",
	"shoppingCart_proceed_ordersummary":" Please wait while Shopping Cart details are being validated...",
	"shoppingCart_place_order":" Please wait while your request is being processed...",
	"shoppingCart_recent_approvers":"Recent Approvers",
	"shoppingCart_change_approver":"Change Approver",
	"shoppingCart_approvers_not_required":"Approval not required for this Shopping Cart",
	"shoppingCart_approver_details":"Approver details",
	"shoppingCart_select_approver":"Select Approver",
	"neFIleadded"
};